---
dxr:
  www_root: '/'
  workers: 4
  default_tree: 'mozilla-central'
  disabled_plugins: 'xpidl'
  enabled_plugins: '*'
  es_hosts:
    - http://node47.bunker.scl3.mozilla.com:9200/
    - http://node48.bunker.scl3.mozilla.com:9200/
    - http://node49.bunker.scl3.mozilla.com:9200/
  es_catalog_replicas: 4
  es_catalog_index: 'dxr_catalog'
  es_index: 'dxr_cold_{format}_{tree}_{unique}'
  es_alias: 'dxr_{format}_{tree}'
  es_indexing_timeout: 120
  es_refresh_interval: 30

defaults:
  disable: false
  schedule: 'H H/4 * * *'
  quiet_period: 3600
  job_weight: 1
  build_command: ''   # DXR's default is 'make ...'
  mail_rcpts: fubar@mozilla.com erose@mozilla.com
  docker_img: 'quay.io/fubar/ubuntu-indexer:latest'
  docker_vol: '/data/dxr_data:/builds/dxr-build-env/src'
  repo_dir: '../../../dxr_data'
  dxr_plugins:
    - plugin: 'python'
      python_path: '/builds/dxr-build-env/venv/lib/python2.7/site-packages'
    - plugin: 'buglink'
      name: 'bugzilla'
      url: 'https://bugzilla.mozilla.org/show_bug.cgi?id=%s'

trees:
  - name: 'mozilla-central'
    repos:
      - url: 'https://hg.mozilla.org/mozilla-central'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    es_index: 'dxr_hot_{format}_{tree}_{unique}'
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && ./mach mercurial-setup -u && ./mach clobber && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'
    plugins:
      - plugin: 'xpidl'
        header_path: 'src/mozilla-central/obj-x86_64-pc-linux-gnu/dist/include'
        include_folders: 'src/mozilla-central/obj-x86_64-pc-linux-gnu/dist/idl'

  - name: 'mozilla-aurora'
    proj_dir: 'releases'
    repos:
      - url: 'https://hg.mozilla.org/releases/mozilla-aurora'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && ./mach mercurial-setup -u && ./mach clobber && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'
    plugins:
      - plugin: 'xpidl'
        header_path: 'src/releases/mozilla-aurora/obj-x86_64-unknown-linux-gnu/dist/include'
        include_folders: 'src/releases/mozilla-aurora/obj-x86_64-unknown-linux-gnu/dist/idl'

  - name: 'mozilla-beta'
    proj_dir: 'releases'
    repos:
      - url: 'https://hg.mozilla.org/releases/mozilla-beta'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && ./mach mercurial-setup -u && ./mach clobber && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'
    plugins:
      - plugin: 'xpidl'
        header_path: 'src/releases/mozilla-beta/obj-x86_64-unknown-linux-gnu/dist/include'
        include_folders: 'src/releases/mozilla-beta/obj-x86_64-unknown-linux-gnu/dist/idl'

  - name: 'mozilla-release'
    proj_dir: 'releases'
    repos:
      - url: 'https://hg.mozilla.org/releases/mozilla-release'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && ./mach mercurial-setup -u && ./mach clobber && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'
    plugins:
      - plugin: 'xpidl'
        header_path: 'src/releases/mozilla-release/obj-x86_64-unknown-linux-gnu/dist/include'
        include_folders: 'src/releases/mozilla-release/obj-x86_64-unknown-linux-gnu/dist/idl'

  - name: 'mozilla-esr45'
    proj_dir: 'releases'
    repos:
      - url: 'https://hg.mozilla.org/releases/mozilla-esr45'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && ./mach mercurial-setup -u && ./mach clobber && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'
    plugins:
      - plugin: 'xpidl'
        header_path: 'src/releases/mozilla-esr45/obj-x86_64-unknown-linux-gnu/dist/include'
        include_folders: 'src/releases/mozilla-esr45/obj-x86_64-unknown-linux-gnu/dist/idl'

  - name: 'comm-central'
    repos:
      - url: 'https://hg.mozilla.org/comm-central'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    es_index: 'dxr_hot_{format}_{tree}_{unique}'
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && python client.py checkout && ./mozilla/mach mercurial-setup -u && ./mozilla/mach clobber && ./mozilla/mach build'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --enable-application=mail'
      - 'ac_add_options --enable-calendar'
      - 'ac_add_options --disable-optimize'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'

  - name: 'build-central'
    proj_dir: 'build'
    job_weight: 2
    build_command: ''
    ignore_patterns: '*.svg .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    repos:
      - url: 'https://hg.mozilla.org/build/braindump'
      - url: 'https://hg.mozilla.org/build/buildapi'
      - url: 'https://hg.mozilla.org/build/buildbot'
      - url: 'https://hg.mozilla.org/build/buildbot-configs'
      - url: 'https://hg.mozilla.org/build/buildbotcustom'
      - url: 'https://github.com/mozilla/build-cloud-tools.git'
        dirname: 'cloud-tools'
      - url: 'https://hg.mozilla.org/build/compare-locales'
      - url: 'https://hg.mozilla.org/build/mozharness'
      - url: 'https://hg.mozilla.org/build/mozpool'
      - url: 'https://hg.mozilla.org/build/nagios-tools'
      - url: 'https://hg.mozilla.org/build/partner-repacks'
      - url: 'https://hg.mozilla.org/build/puppet'
      - url: 'https://hg.mozilla.org/build/relabs-puppet'
      - url: 'https://github.com/mozilla/build-relengapi'
        dirname: 'relengapi'
      - url: 'https://hg.mozilla.org/build/serveS3'
      - url: 'https://git.mozilla.org/build/slaveapi'
      - url: 'https://hg.mozilla.org/build/slave_health'
      - url: 'https://hg.mozilla.org/build/talos'
      - url: 'https://hg.mozilla.org/build/tools'
      - url: 'https://hg.mozilla.org/build/tupperware'
      - url: 'https://hg.mozilla.org/build/twisted'

  - name: 'hgcustom_version-control-tools'
    proj_dir: 'hgcustom'
    repos:
      - url: 'https://hg.mozilla.org/hgcustom/version-control-tools'

  - name: 'rust'
    proj_dir: 'rust-lang'
    repos:
      - url: 'https://github.com/rust-lang/rust.git'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    es_index: 'dxr_hot_{format}_{tree}_{unique}'
    enabled_plugins: 'pygmentize rust buglink omniglot'
    ignore_patterns: '/compiletest/ /doc/ /etc/ /gyp/ .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && ./configure --disable-libcpp --enable-ccache --enable-clang && make clean && make -j4'
    plugins:
      - plugin: 'buglink'
        name: 'github'
        url: 'https://github.com/rust-lang/rust/issues/%s'
        regex: '#([0-9]+)'

  - name: 'rustfmt'
    repos:
      - url: 'https://github.com/rust-lang-nursery/rustfmt.git'
    enabled_plugins: 'pygmentize rust buglink'
    ignore_patterns: '/target/ /tests/ /data/ .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder/src && RUSTC=/builds/dxr-build-env/dxr/dxr/plugins/rust/dxr-rustc.sh cargo build --verbose'
    plugins:
      - plugin: 'buglink'
        name: 'github'
        url: 'https://github.com/rust-lang-nursery/rustfmt/issues/%s'
        regex: '#([0-9]+)'

  - name: 'nss'
    proj_dir: 'nss'
    repos:
      - url: 'https://hg.mozilla.org/projects/nss'
      - url: 'https://hg.mozilla.org/projects/nspr'
    job_weight: 2
    build_command: 'cd $source_folder/nss && env CPATH=/usr/include/x86_64-linux-gnu make NS_USE_GCC=0 CC=clang CXX=clang++ USE_64=1 NSS_DISABLE_GTESTS=1 nss_build_all'

